img_dim: [416, 416]
grid_dim: [13, 13]
box: 5
n_class: 1
obj_thresh: 0.3
nms_thresh: 0.3
anchors: [0.57273, 0.677385, 1.87446, 2.06253, 3.33843, 5.47434, 7.88282, 3.52778, 9.77052, 9.16828]
no_obj_scale: 1.0
obj_scale: 1.0
coord_scale: 1.0
class_scale: 1.0

batch_size: 16
warm_ups: 0
true_box_buff: 50

weight_path: 'data/weights/yolo.weights'
train_path_img: 'data/train/img/' 
train_path_ann: 'data/train/ann/' 
valid_path_img: 'data/valid/img/' 
valid_path_ann: 'data/valid/ann/' 