# Input image size [width, height]
image: [150, 150]

# Input data paths
train_raw_dir: 'data/train/img/'
train_anno_dir: 'data/train/ann/'
valid_raw_dir: 'data/valid/img/'
valid_anno_dir: 'data/valid/ann/'

# Input data sample size
train_samples: 1000
valid_samples: 400

# Training parameters
epochs: 1000
batch_size: 16
learning_rate: 0.0001
