#Directories, etc
dataset_folder: 'data\dataset\'
train_output: 'train.csv'
validation_output: 'validation.csv'
dictionary_output: 'dictionary.txt'
anno_folder: 'data\anno\'
classes: {
  'key' : 1
}

#Dataset Variables
gen_dataset: True
split_ratio: 0.8
max_classes: 2

aug: True
aug_debug: False
aug_per_img: 25
aug_folder: 'data\aug\'

#Training Variables
train_model: True
alpha: 0.25
img_size: [128, 128] #figure out dimensionality problems
epochs: 5000
patience: 100

#Testing
debug: False
weights: ''